# Generated by Django 5.2.7 on 2025-10-19 15:00

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone

DEFAULT_COLUMNS = (
    ("Backlog", 0),
    ("In Progress", 1),
    ("Review", 2),
    ("Done", 3),
)


def create_default_board(apps, schema_editor):
    Board = apps.get_model("board", "Board")
    Column = apps.get_model("board", "Column")
    db_alias = schema_editor.connection.alias

    board, _ = Board.objects.using(db_alias).get_or_create(
        name="Mein Board",
        defaults={"created_at": timezone.now()},
    )

    column_qs = Column.objects.using(db_alias)
    if not column_qs.exists():
        column_qs.bulk_create(
            [
                Column(name=name, order=order, board=board)
                for name, order in DEFAULT_COLUMNS
            ]
        )
    else:
        column_qs.filter(board__isnull=True).update(board=board)


def revert_default_board(apps, schema_editor):
    Board = apps.get_model("board", "Board")
    Column = apps.get_model("board", "Column")
    db_alias = schema_editor.connection.alias

    Column.objects.using(db_alias).update(board=None)
    Board.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0002_card_assignee_card_due_date_card_priority"),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddField(
            model_name="column",
            name="board",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="columns",
                to="board.board",
            ),
        ),
        migrations.RunPython(create_default_board, revert_default_board),
        migrations.AlterField(
            model_name="column",
            name="board",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="columns",
                to="board.board",
            ),
        ),
    ]

